//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccidentDetail
    {
        public int AccidentDetailID { get; set; }
        public int PersonID { get; set; }
        public short AccidentTypeID { get; set; }
        public string DateOfAccident { get; set; }
        public string TimeOfAccident { get; set; }
        public string Location { get; set; }
    
        public virtual AccidentType AccidentType { get; set; }
        public virtual PatientDemographic PatientDemographic { get; set; }
    }
}
