//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PatientDemosGridView
    {
        public int PersonID { get; set; }
        public short HospitalID { get; set; }
        public string HospitalName { get; set; }
        public Nullable<bool> In_Hospital_Directory { get; set; }
        public string HospitalService { get; set; }
        public string PrimaryCarePhys { get; set; }
        public System.DateTime AdmitDate { get; set; }
        public Nullable<bool> PatientHereBefore { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Entitlement { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string Status { get; set; }
    }
}
