//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceAttachment
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int InsId { get; set; }
        public string FileName { get; set; }
    }
}
