//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsibleParty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResponsibleParty()
        {
            this.MinorInformations = new HashSet<MinorInformation>();
        }
    
        public int ResponsiblePartyID { get; set; }
        public string ResponsiblePartyDescription { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinorInformation> MinorInformations { get; set; }
    }
}
